### ISSUE TITLE
Thumbnail does not appear under chrome

### ISSUE THREAD

**Issue by venomone** [phloxic/videojs-sprite-thumbnails#30]
Hello,

I would like to know why I don't see any sprites in chrome, where Firefox seems to work fine!?
Is this already a known issue?

Thanks in advance

**Comment by phloxic** [comment]
@venomone - works fine in Chrome for me[tm]. Could you be more specific? Link to an example where this happens?

**Comment by venomone** [comment]
Sadly I dont have any example online :( But is this only CSS controlled? The only really diffrence I see is that with chrome I get the following at my browsers console:

`VIDEOJS: video-player: spriteThumbnails: WARN: connection.downlink < 2`

This message does not appear with Firefox. Any Idea?

**Comment by phloxic** [comment]
See the `downlink` [config option](https://github.com/phloxic/videojs-sprite-thumbnails#configuration).

This is expected behaviour. You are on a rather slow connection, so Chrome does not load thumbnails to avoid interfering with playback. At the moment only Chrome based browsers [support the network connection interface](hhttps://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/downlink#browser_compatibility), so Firefox loads and shows them.

You can can of course also disable this check.
