### ISSUE TITLE
Latest version (2.2.0) not working in Safari and Firefox

### ISSUE THREAD

**Issue by iblack10** [phloxic/videojs-sprite-thumbnails#61]
Thanks for the awesome plugin.

In my experience the latest version is no longer displaying thumbnails in Safari and Firefox.
I've put together a very rough example which should work correctly in Chrome but not in the others:

https://jsfiddle.net/s2da0goh/

Downgrading to v2.1.1 will work.

**Comment by phloxic** [comment]
Thank you for the example, @iblack10

For me it also does not work in Chrome. I thought I had this kind of setup covered, but obviously I didn't. Will look into it as soon as possible, but it may take a couple of weeks because of other commitments.

If you can make do with 2.1.1 in the meantime, that would be grand.

Aside: for single sprites do not set `rows`.

**Comment by iblack10** [comment]
Thanks so much for the quick fix!
